database: h2

# server
server:
  error:
    include-stacktrace: always
    include-exception: true
    whitelabel:
      enabled: false
  port: 9090

# spring
spring:
  # db 설정
  datasource:
    schema: classpath*:db/${database}/schema.sql
    data: classpath*:db/${database}/data.sql
  # JPA
  jpa:
    database: ${database}
    open-in-view: false
    hibernate:
      ddl-auto: none
#  # mvc
#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .html
logging:
  file:
    path: logs/apiserver
  level:
    org.hibernate: error
    org.springframework: info
    org.springframework.web: info
    com.plzhans.assignment.api:
      controller.ErrorController: error



