######################################
# mysql
######################################
database: mysql
spring:
    profiles: mysql
    datasource:
        url: jdbc:mysql://localhost:13306/assignment
        username: assignment
        password: assignment
    jpa:
        database: ${database}
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect