######################################
# debug
######################################
spring:
  profiles: debug
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  # JPA
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
#    org.hibernate: debug
    org.hibernate:
      type:
        descriptor:
          sql: trace
    org.springframework: debug
    org.springframework.web: debug
